n=readline(prompt="Enter your NAME: ")
r=readline(prompt="Enter your ROllno: ")
m1=as.numeric(readline(prompt="Enter your first subject mark: "))
m2=as.numeric(readline(prompt="Enter your second subject mark: "))
m3=as.numeric(readline(prompt="Enter your thrid subject mark: "))
tot=as.numeric(m1+m2+m3)
ave=as.numeric(tot/3)
cat("Your name: ",n)
cat("Your Rollno: ",r)
cat("Your Total: ",tot)
cat("Your Average: ",ave)